In [5]:
class animal():
    '''this is doc'''
    def __init__(self,name,kind):
        self.name=name
        self.kind=kind
    def getName(self):
        return self.name
    def getKind(self):
        return self.kind
    def changeName(self,new_name):
        self.name=new_name

In [3]:
A=animal("cat","cat_kind")

In [6]:
A.__doc__

In [7]:
A.__doc__

In [9]:
class animal():
    '''this is doc'''
    def __init__(self,name,kind):
        self.name=name
        self.kind=kind
    def getName(self):
        '''a method'''
        return self.name
    def getKind(self):
        return self.kind
    def changeName(self,new_name):
        self.name=new_name

In [10]:
A=animal("cat","cat_kind")

In [11]:
A.__doc__

'this is doc'

In [12]:
dir(A.getName)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__func__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

In [13]:
A.getName.__doc__

'a method'

In [14]:
help(animal)

Help on class animal in module __main__:

class animal(builtins.object)
 |  this is doc
 |  
 |  Methods defined here:
 |  
 |  __init__(self, name, kind)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  changeName(self, new_name)
 |  
 |  getKind(self)
 |  
 |  getName(self)
 |      a method
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)



In [15]:
class animal():
    '''this is doc'''
    def __init__(self,name,kind):
        self.name=name
        self.kind=kind
    def getName(self):
        '''a method'''
        return self.name
    def getKind(self):
        return self.kind
    def changeName(self,new_name):
        self.name=new_name
    def __str__(self):
        print(self.name,'---',self.kind)

In [16]:
A=animal("cat","cat_kind")

In [17]:
print(A)

cat --- cat_kind


TypeError: __str__ returned non-string (type NoneType)

In [18]:
class animal():
    '''this is doc'''
    def __init__(self,name,kind):
        self.name=name
        self.kind=kind
    def getName(self):
        '''a method'''
        return self.name
    def getKind(self):
        return self.kind
    def changeName(self,new_name):
        self.name=new_name
    def __str__(self):
        return self.name,'---',self.kind

In [19]:
A=animal("cat","cat_kind")

In [20]:
print(A)

TypeError: __str__ returned non-string (type tuple)

In [21]:
class animal():
    '''this is doc'''
    def __init__(self,name,kind):
        self.name=name
        self.kind=kind
    def getName(self):
        '''a method'''
        return self.name
    def getKind(self):
        return self.kind
    def changeName(self,new_name):
        self.name=new_name
    def __str__(self):
        print(self.name+'---'+self.kind)

In [22]:
A=animal("cat","cat_kind")

In [23]:
print(A)

cat---cat_kind


TypeError: __str__ returned non-string (type NoneType)

In [24]:
class animal():
    '''this is doc'''
    def __init__(self,name,kind):
        self.name=name
        self.kind=kind
    def getName(self):
        '''a method'''
        return self.name
    def getKind(self):
        return self.kind
    def changeName(self,new_name):
        self.name=new_name
    def __str__(self):
        return (self.name+'---'+self.kind)

In [25]:
A=animal("cat","cat_kind")

In [26]:
print(A)

cat---cat_kind


In [27]:
class cat(animal):
    def __init__():
        pass

In [28]:
class cat_asia(cat):
    def __init__():
        pass

In [29]:
from numpy import array

In [30]:
a=array([[0, 1, 2, 3, 4, 5],
        [10,11,12,13,14,15],
        [20,21,22,23,24,25],
        [30,31,32,33,34,35],
        [40,41,42,43,44,45],
        [50,51,52,53,54,55]])

In [31]:
import numpy as np

In [32]:
a[2,3]

23

In [33]:
a[0]

array([0, 1, 2, 3, 4, 5])

In [34]:
a[:0]

array([], shape=(0, 6), dtype=int32)

In [35]:
a[:,0]

array([ 0, 10, 20, 30, 40, 50])

In [36]:
a[,0]

SyntaxError: invalid syntax (<ipython-input-36-241a3fa00b9e>, line 1)

In [37]:
a[0,:]

array([0, 1, 2, 3, 4, 5])

In [38]:
a[3,:]

array([30, 31, 32, 33, 34, 35])

In [39]:
a[3,2:4]

array([32, 33])

In [40]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [41]:
a[::2,::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [42]:
a[(0,2,3),::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [30, 32, 34]])

In [43]:
a.max()

55

In [44]:
a.sum()

990

In [45]:
a.std()

17.163430115607234

In [46]:
a.var()

294.5833333333333

In [47]:
a.mean()

27.5

In [49]:
a.any()

True

In [53]:
a=np.zeros((15,15),dtype=float)

In [54]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [55]:
a=np.linespace(0,100,5)

AttributeError: module 'numpy' has no attribute 'linespace'

In [56]:
b = np.linspace(0,100,5)

In [57]:
b

array([  0.,  25.,  50.,  75., 100.])